name: Deploy Rocker
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸª„ Checkout repository
        uses: actions/checkout@v4
      - name: ðŸª… Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            export COMPOSER_ALLOW_SUPERUSER=1 && \
            cd /var/www/rocker.am && \
            git pull && \
            composer install --no-interaction --prefer-dist --optimize-autoloader && \
            npm ci && \
            npm audit fix || true && \
            npm run build && \
            php artisan migrate --force && \
            pm2 restart rocker